=== fmilica/XML_i_web_servisi/modelovani_dokumenti/obavestenje/obavestenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://" xmlns:obv="http://">
    <xs:element name="Obavestenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Organ_vlasti" type="obv:TOrgan_vlasti"> </xs:element>
                <xs:element name="Broj_predmeta" type="xs:string"> </xs:element>
                <xs:element name="Podnosilac" type="obv:TLice"/>
                <xs:element name="Uvid_u_dokument">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="Zakonska_osnova" type="obv:TZakon"> </xs:element>
                            <xs:element name="Datum_potrazivanja" type="xs:date"/>
                            <xs:element name="Opis_trazene_informacije" type="xs:string"/>
                            <xs:element name="Podaci_o_uvidu" type="obv:TVremeMesto"> </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Ukupan_trosak_kopija">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:double">
                                <xs:attribute fixed="RSD" name="valuta">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:length value="3"/>
                                            <xs:pattern value="[A-Z]{3}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute fixed="840-742328-843-30" name="ziro_racun"
                                    type="xs:string"/>
                                <xs:attribute default="97" name="poziv_na_broj">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:length value="2"/>
                                            <xs:pattern value="[0-9]{2}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="dostavljeno" type="obv:TDostavljeno" use="required"/>
            <xs:attribute name="datum" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="Mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([A-Z][a-z]+)(\s[A-Z][a-z]+)*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([A-Z][a-z]+)(\s[A-Z]?[a-z]+)*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Ulicni_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([1-9][0-9]*)|(bb)"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAdresa_uvida">
        <xs:complexContent>
            <xs:extension base="obv:TAdresa">
                <xs:sequence>
                    <xs:element name="Kancelarijski_broj" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TOrgan_vlasti">
        <xs:sequence>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element name="Sediste">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([A-Z][a-z]+)(\s[A-Z][a-z]+)*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TLice">
        <xs:sequence>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime" type="xs:string"/>
                </xs:sequence>
                <xs:element name="Naziv" type="xs:string"/>
            </xs:choice>
            <xs:element name="Adresa" type="obv:TAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TDostavljeno">
        <xs:restriction base="xs:string">
            <xs:enumeration value="imenovanom"/>
            <xs:enumeration value="arhivi"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TZakon">
        <xs:sequence>
            <xs:element name="Clan" type="xs:positiveInteger" fixed="16"/>
            <xs:element name="Stav" type="xs:positiveInteger" fixed="1"/>
            <xs:element name="Zakon" type="xs:string"
                fixed="Zakon o slobodnom pristupu informacijama od javnog značaja"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVremeMesto">
        <xs:sequence>
            <xs:element name="Datum" type="xs:date"/>
            <xs:element name="Vreme" type="xs:time"/>
            <xs:element name="Pocetno_vreme">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="23"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Krajnje_vreme">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="23"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Mesto_uvida" type="obv:TAdresa_uvida"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Cene_kopiranja">
        <xs:complexType>
            <xs:sequence>
                <xs:element fixed="3" name="A4" type="xs:positiveInteger"/>
                <xs:element fixed="6" name="A3" type="xs:positiveInteger"/>
                <xs:element fixed="35" name="CD" type="xs:positiveInteger"/>
                <xs:element fixed="20" name="Disketa" type="xs:positiveInteger"/>
                <xs:element fixed="40" name="DVD" type="xs:positiveInteger"/>
                <xs:element fixed="150" name="Audio-kaseta" type="xs:positiveInteger"/>
                <xs:element fixed="300" name="Video-kaseta" type="xs:positiveInteger"/>
                <xs:element fixed="30" name="Skeniranje" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fmilica/XML_i_web_servisi/modelovani_dokumenti/obavestenje/obavestenje_gen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Obavestenje xmlns="http://obavestenje"
    xmlns:tipovi="http://tipovi"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://obavestenje obavestenje.xsd" 
    dostavljeno="imenovanom" 
    datum="2006-05-04"
    id="ID002">
    <Organ_vlasti>
        <tipovi:Naziv>Fakultet tehnickih nauka</tipovi:Naziv>
        <tipovi:Sediste>Novi Sad</tipovi:Sediste>
    </Organ_vlasti>
    <Broj_predmeta>SIIT-1</Broj_predmeta>
    <Podnosilac>
        <tipovi:Ime>Vlastislav</tipovi:Ime>
        <tipovi:Prezime>Jakovljevic</tipovi:Prezime>
        <tipovi:Adresa>
            <tipovi:Mesto>Novi Sad</tipovi:Mesto>
            <tipovi:Ulica>Zeleznicka</tipovi:Ulica>
            <tipovi:Ulicni_broj>23</tipovi:Ulicni_broj>
        </tipovi:Adresa>
    </Podnosilac>
    <Uvid_u_dokument>
        <Zakonska_osnova>
            <Clan>16</Clan>
            <Stav>1</Stav>
            <Zakon>Zakon o slobodnom pristupu informacijama od javnog znaƒçaja</Zakon>
        </Zakonska_osnova>
        <Datum_potrazivanja>2006-05-04</Datum_potrazivanja>
        <Opis_trazene_informacije>Informacije o polozenim predmetima</Opis_trazene_informacije>
        <Podaci_o_uvidu>
            <Datum>2006-05-04</Datum>
            <Vreme>15:30:00.000</Vreme>
            <Pocetno_vreme>12</Pocetno_vreme>
            <Krajnje_vreme>17</Krajnje_vreme>
            <Mesto_uvida>
                <tipovi:Mesto>Novi Sad</tipovi:Mesto>
                <tipovi:Ulica>Trg Dositeja Obradovica</tipovi:Ulica>
                <tipovi:Ulicni_broj>4</tipovi:Ulicni_broj>
                <Kancelarijski_broj>F-13</Kancelarijski_broj>
            </Mesto_uvida>
        </Podaci_o_uvidu>
    </Uvid_u_dokument>
    <Ukupan_trosak_kopija valuta="RSD" ziro_racun="840-742328-843-30" poziv_na_broj="97">30</Ukupan_trosak_kopija>
</Obavestenje>

=== fmilica/XML_i_web_servisi/servisi/poverenik/backend/src/main/resources/data/obavestenje_gen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<obv:Obavestenje xmlns="http://www.w3.org/ns/rdfa#"
    xmlns:obv="http://obavestenje"
    xmlns:tipovi="http://tipovi"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.xml.com/predicate/"
    xsi:schemaLocation="http://obavestenje schema/obavestenje/obavestenje.xsd" 
    dostavljeno="imenovanom" 
    datum="2006-05-04"
    id="ID1"
    
    vocab="http://www.xml.com/predicate/"
    about="http://obavestenje/ID1"
    rel="pred:vezanZahtev"
    href="http://zahtev/ID1"
    >
    <obv:Organ_vlasti>
        <tipovi:Naziv property="pred:izdavacNaziv">Fakultet tehnickih nauka</tipovi:Naziv>
        <tipovi:Sediste>Novi Sad</tipovi:Sediste>
    </obv:Organ_vlasti>
    <obv:Broj_predmeta>SIIT-1</obv:Broj_predmeta>
    <obv:Podnosilac>
        <tipovi:Ime property="pred:podnosilacIme">Vlastislav</tipovi:Ime>
        <tipovi:Prezime property="pred:podnosilacPrezime">Jakovljevic</tipovi:Prezime>
        <tipovi:Adresa>
            <tipovi:Mesto>Novi Sad</tipovi:Mesto>
            <tipovi:Ulica>Zeleznicka</tipovi:Ulica>
            <tipovi:Ulicni_broj>23</tipovi:Ulicni_broj>
        </tipovi:Adresa>
    </obv:Podnosilac>
    <obv:Uvid_u_dokument>
        <obv:Zakonska_osnova>
            <obv:Clan>16</obv:Clan>
            <obv:Stav>1</obv:Stav>
            <obv:Zakon>Zakon o slobodnom pristupu informacijama od javnog znaƒçaja</obv:Zakon>
        </obv:Zakonska_osnova>
        <obv:Datum_potrazivanja>2006-05-04</obv:Datum_potrazivanja>
        <obv:Opis_trazene_informacije>Informacije o polozenim predmetima</obv:Opis_trazene_informacije>
        <obv:Podaci_o_uvidu>
            <obv:Datum>2006-05-04</obv:Datum>
            <obv:Vreme>15:30:00.000</obv:Vreme>
            <obv:Pocetno_vreme>12</obv:Pocetno_vreme>
            <obv:Krajnje_vreme>17</obv:Krajnje_vreme>
            <obv:Mesto_uvida>
                <tipovi:Mesto>Novi Sad</tipovi:Mesto>
                <tipovi:Ulica>Trg Dositeja Obradovica</tipovi:Ulica>
                <tipovi:Ulicni_broj>4</tipovi:Ulicni_broj>
                <obv:Kancelarijski_broj>F-13</obv:Kancelarijski_broj>
            </obv:Mesto_uvida>
        </obv:Podaci_o_uvidu>
    </obv:Uvid_u_dokument>
    <obv:Ukupan_trosak_kopija valuta="RSD" ziro_racun="840-742328-843-30" poziv_na_broj="97">30</obv:Ukupan_trosak_kopija>
</obv:Obavestenje>
