=== fmilica/XML_i_web_servisi/modelovani_dokumenti/obavestenje/obavestenje.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT obavestenje_o_uvidu  (zaglavlje_obavestenja, telo_obavestenja) >
<!ATTLIST obavestenje_o_uvidu obavestenjeID ID #REQUIRED >

<!-- POCETAK ZAGLAVLJA -->
<!ELEMENT zaglavlje_obavestenja (podaci_o_organu, podaci_o_predmetu, podaci_o_podnosiocu) >

<!ELEMENT podaci_o_organu (naziv_organa, sediste_organa) >
<!ELEMENT naziv_organa (#PCDATA) >
<!ATTLIST naziv_organa organID ID #REQUIRED >
<!ELEMENT sediste_organa (#PCDATA) >

<!ELEMENT podaci_o_predmetu (broj_predmeta, datum_nastanka_predmeta) >
<!ELEMENT broj_predmeta  (#PCDATA)>
<!ATTLIST broj_predmeta brojPredmetaID ID #REQUIRED >
<!ELEMENT datum_nastanka_predmeta (#PCDATA) >

<!ELEMENT podaci_o_podnosiocu (((ime_podnosioca, prezime_podnosioca) | naziv_podnosioca), adresa_podnosioca) >
<!ELEMENT ime_podnosioca (#PCDATA) >
<!ELEMENT prezime_podnosioca (#PCDATA) >
<!ELEMENT naziv_podnosioca (#PCDATA) >
<!ELEMENT adresa_podnosioca (postanski_broj, mesto, ulica, ulicni_broj) >
<!ELEMENT postanski_broj (#PCDATA) >
<!ELEMENT mesto (#PCDATA) >
<!ELEMENT ulica (#PCDATA) >
<!ELEMENT ulicni_broj (#PCDATA) >
<!-- KRAJ ZAGLAVLJA -->

<!-- POCETAK TELA  -->
<!ELEMENT telo_obavestenja (naslov, sadrzaj_obavestenja) >

<!ELEMENT naslov (tip_dokumenta, opis_dokumenta) >
<!ELEMENT tip_dokumenta (#PCDATA) >
<!ELEMENT opis_dokumenta (#PCDATA) >

<!ELEMENT sadrzaj_obavestenja (uvid_u_dokument, kopiranje_dokumenta, dostavljeno) >

<!ELEMENT uvid_u_dokument (#PCDATA | zakon | datum_potrazivanja |
                            opis_trazene_informacije | podaci_o_uvidu)* >

<!ELEMENT zakon (#PCDATA | clan)* >
<!ELEMENT clan (#PCDATA | stav)* >
<!ELEMENT stav (#PCDATA) >

<!ELEMENT datum_potrazivanja (#PCDATA) >
<!ELEMENT opis_trazene_informacije (#PCDATA) >

<!ELEMENT podaci_o_uvidu (#PCDATA | datum | vreme | 
                            pocetno_vreme | krajnje_vreme | 
                            mesto_uvida | ulica_uvida | ulicni_broj_uvida | 
                            kancelarijski_broj_uvida)* >
<!ELEMENT datum (#PCDATA) >
<!ELEMENT vreme (#PCDATA) >
<!ELEMENT pocetno_vreme (#PCDATA) >
<!ELEMENT krajnje_vreme (#PCDATA) >
<!ELEMENT mesto_uvida (#PCDATA) >
<!ELEMENT ulica_uvida (#PCDATA) >
<!ELEMENT ulicni_broj_uvida (#PCDATA) >
<!ELEMENT kancelarijski_broj_uvida (#PCDATA) >

<!ELEMENT kopiranje_dokumenta (#PCDATA | ukupan_trosak_kopija)* >
<!ELEMENT ukupan_trosak_kopija (#PCDATA) >
<!ATTLIST ukupan_trosak_kopija valuta CDATA #FIXED "RSD" >
<!ATTLIST ukupan_trosak_kopija ziro_racun CDATA #FIXED "840-742328-843-30" >
<!ATTLIST ukupan_trosak_kopija poziv_na_broj CDATA #FIXED "97" >

<!ELEMENT dostavljeno (#PCDATA) >
<!-- KRAJ TELA -->

=== fmilica/XML_i_web_servisi/modelovani_dokumenti/obavestenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE obavestenje_o_uvidu SYSTEM "obavestenje.dtd" >

<obavestenje_o_uvidu obavestenjeID="obvID1">
    <zaglavlje_obavestenja>
        <podaci_o_organu>
            <naziv_organa organID="orgID1">...</naziv_organa>
            <!-- JEL SEDISTE SAMO GRAD -->
            <sediste_organa>...</sediste_organa>
        </podaci_o_organu>
        <podaci_o_predmetu>
            <broj_predmeta brojPredmetaID="prdID1">...</broj_predmeta>
            <!-- da li je ovo datum nastanka predmeta ili trenutni datum -->
            <datum_nastanka_predmeta>...</datum_nastanka_predmeta>
        </podaci_o_predmetu>
        <!-- DA LI OVDE UBACITI ID PODNOSIOCA??? -->
        <podaci_o_podnosiocu>
            <ime_podnosioca>...</ime_podnosioca>
            <prezime_podnosioca>...</prezime_podnosioca>
            <!-- ILI (IME I PREZIME) ILI NAZIV 
            <naziv_podnosioca>...</naziv_podnosioca> -->
            <adresa_podnosioca>
                <postanski_broj></postanski_broj>
                <mesto></mesto>
                <ulica></ulica>
                <ulicni_broj></ulicni_broj>
            </adresa_podnosioca>
        </podaci_o_podnosiocu>
    </zaglavlje_obavestenja>
    <telo_obavestenja>
        <naslov>
            <tip_dokumenta>О Б А В Е Ш Т Е Њ Е</tip_dokumenta>
            <opis_dokumenta>о стављању на увид документа који садржи
                тражену информацију и о изради копије
            </opis_dokumenta>
        </naslov>
        <sadrzaj_obavestenja>
            <uvid_u_dokument>
                На основу 
                <zakon>
                    <clan>
                        члана 16. 
                        <stav>ст. 1.</stav>
                    </clan> 
                    Закона о слободном приступу информацијама од јавног значаја
                </zakon>, поступајући по вашем захтеву за слободан приступ информацијама од 
                <datum_potrazivanja>...</datum_potrazivanja>
                год., којим сте тражили увид у документ/е са информацијама о / у вези са: 
                <opis_trazene_informacije>...</opis_trazene_informacije>
                (опис тражене информације)
                обавештавамо вас да дана 
                <podaci_o_uvidu>
                    <datum>...</datum>
                    , у 
                    <vreme>...</vreme>
                    часова, односно у времену од 
                    <pocetno_vreme>...</pocetno_vreme>
                    до 
                    <krajnje_vreme>...</krajnje_vreme>
                    часова, у просторијама органа у 
                    <mesto_uvida>...</mesto_uvida>
                    ул. 
                    <ulica_uvida>...</ulica_uvida>
                    бр.
                    <ulicni_broj_uvida>...</ulicni_broj_uvida>
                    , канцеларија бр. 
                    <kancelarijski_broj_uvida>...</kancelarijski_broj_uvida>
                    можете извршити увид у документ/е у коме је садржана тражена информација.
                </podaci_o_uvidu>
            </uvid_u_dokument>
            <kopiranje_dokumenta>
                Том приликом, на ваш захтев, може вам се издати и копија документа са траженом 
                информацијом.
                <!-- da li je neophodno ovde napraviti tag za sluzbeni glasnik i uredbu? - isto pitanje i na kraju pasusa -->
                Трошкови су утврђени Уредбом Владе Републике Србије („Сл. гласник РС“, бр. 8/06), и то: 
                копија стране А4 формата износи 3 динара, А3 формата 6 динара, CD 35 динара, дискете 20 
                динара, DVD 40 динара, аудио-касета – 150 динара, видео-касета 300 динара, претварање 
                једне стране документа из физичког у електронски облик – 30 динара.
                
                Износ укупних трошкова израде копије документа по вашем захтеву износи
                <ukupan_trosak_kopija valuta="RSD" ziro_racun="840-742328-843-30" poziv_na_broj="97">...</ukupan_trosak_kopija>
                динара и уплаћује се на жиро-рачун Буџета Републике Србије бр. 840-742328-843-30, с 
                позивом на број 97 – ознака шифре општине/града где се налази орган власти (из 
                Правилника о условима и начину вођења рачуна – „Сл. гласник РС“, 20/07... 40/10).
            </kopiranje_dokumenta>
            <dostavljeno>
                <!-- ovde se zaokruzuje kome je dostavljeno, kako to u elektronskom obliku
                da popunjavamo dinamicki u zavisnosti kome saljemo dokument?
                jel to uopste moguce?-->
                Достављено:
                1. Именованом 
                2. Архиви
            </dostavljeno>
        </sadrzaj_obavestenja>
    </telo_obavestenja>
</obavestenje_o_uvidu>
