=== fmilica/XML_i_web_servisi/XML_POC/data/resenje/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://resenje" xmlns:res="http://resenje" xmlns:tipovi="http://tipovi"
    xmlns:rdfa="http://www.w3.org/ns/rdfa#"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
    <xs:import namespace="http://tipovi" schemaLocation="../tipovi.xsd"/>
    <xs:element name="Resenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="res:Opis_zalbe"/>
                <xs:element ref="res:Odluka"/>
                <xs:element ref="res:Obrazlozenje"/>
                <xs:element name="Poverenik" type="res:TOsoba"/>
            </xs:sequence>
            <xs:attribute name="broj_resenja" use="required" type="xs:string"> </xs:attribute>
            <xs:attribute name="datum_resenja" type="xs:date" use="required"/>
            <xs:attribute name="tip_odluke" type="res:Tip_odluke" use="required"/>
            <xs:attribute name="id" type="xs:string" use="optional"/>
            <xs:attribute name="vocab" type="xs:string"/>
            <xs:attribute name="about" type="xs:string"/>
            <xs:attribute name="rel" type="xs:string"/>
            <xs:attribute name="href" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Opis_zalbe">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:choice minOccurs="0">
                    <xs:sequence>
                        <xs:element name="Ime_zalilac">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="property"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="Prezime_zalilac">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="property"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:element name="Naziv_zalilac">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute name="property" type="xs:string"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="Naziv_organa_vlasti" minOccurs="0">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Mesto_organa_vlasti" type="xs:string" minOccurs="0"> </xs:element>
                <xs:element name="Ulica_organa_vlasti" type="xs:string" minOccurs="0"> </xs:element>
                <xs:element name="Ulicni_broj_organa_vlasti" type="xs:string" minOccurs="0"> </xs:element>
                <xs:element name="Clan" type="xs:positiveInteger" maxOccurs="unbounded"
                    minOccurs="0"/>
                <xs:element minOccurs="0" name="Stav" type="xs:positiveInteger"
                    maxOccurs="unbounded"/>
                <xs:element minOccurs="0" name="Tacka" type="xs:positiveInteger"
                    maxOccurs="unbounded"/>
                <xs:element name="Zakon" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element minOccurs="0" name="Naziv_sluzbenog_glasnika" type="xs:string"
                    maxOccurs="unbounded"> </xs:element>
                <xs:element minOccurs="0" name="Broj_sluzbenog_glasnika" type="xs:string"
                    maxOccurs="unbounded"> </xs:element>
            </xs:sequence>
            <xs:attribute name="razlog_zalbe" type="res:Razlog_zalbe" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odluka">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0">
                <xs:element maxOccurs="unbounded" ref="res:Nalog"/>
                <xs:element name="Odbijanje" type="xs:string"> </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Nalog">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="rok_izvrsenja" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Obrazlozenje">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element ref="res:Postupak_zalioca" minOccurs="0"/>
                <xs:element ref="res:Prosledjivanje_zalbe" minOccurs="0"/>
                <xs:element ref="res:Izjasnjenje_o_zalbi" minOccurs="0"/>
                <xs:element ref="res:Razlozi_odluke" minOccurs="0"/>
                <xs:element ref="res:Zalba_na_resenje" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Postupak_zalioca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podnosenje_zalbe">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="datum_zalbe" type="xs:date" use="required"/>
                                <xs:attribute name="vocab" type="xs:string"/>
                                <xs:attribute name="about" type="xs:string"/>
                                <xs:attribute name="rel" type="xs:string"/>
                                <xs:attribute name="href" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podnosenje_zahteva">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="datum_zahteva" type="xs:date" use="required"/>
                                <xs:attribute name="vocab" type="xs:string"/>
                                <xs:attribute name="about" type="xs:string"/>
                                <xs:attribute name="rel" type="xs:string"/>
                                <xs:attribute name="href" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Prosledjivanje_zalbe">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="Clan" type="xs:positiveInteger" maxOccurs="unbounded"
                        minOccurs="0"/>
                    <xs:element minOccurs="0" name="Stav" type="xs:positiveInteger"
                        maxOccurs="unbounded"/>
                    <xs:element minOccurs="0" name="Tacka" type="xs:positiveInteger"
                        maxOccurs="unbounded"/>
                    <xs:element name="Zakon" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="datum_prosledjivanja" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Izjasnjenje_o_zalbi">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="datum_izjasnjenja" type="xs:date"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Razlozi_odluke">
        <xs:complexType mixed="true">
            <xs:sequence minOccurs="0">
                <xs:element name="Detaljan_opis_podnetog_zahteva" type="xs:string"/>
                <xs:element name="Detaljan_opis_odgovora_na_zahtev" type="xs:string"/>
                <xs:element name="Detaljan_opis_odluke" type="xs:string"/>
                <xs:element name="Clan" type="xs:positiveInteger" maxOccurs="unbounded"
                    minOccurs="0"/>
                <xs:element minOccurs="0" name="Stav" type="xs:positiveInteger"
                    maxOccurs="unbounded"/>
                <xs:element minOccurs="0" name="Tacka" type="xs:positiveInteger"
                    maxOccurs="unbounded"/>
                <xs:element name="Zakon" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element
        default="Против овог решења није допуштена жалба већ се, у складу са Законом о управним споровима, може покренути управни спор тужбом Управном суду у Београду, у року од 30 дана од дана пријема решења. Такса на тужбу износи 390,00 динара."
        name="Zalba_na_resenje">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute default="30" name="rok_za_tuzbu" type="xs:positiveInteger"/>
                    <xs:attribute default="390.00" name="taksa_tuzbe" type="xs:double"/>
                    <xs:attribute default="Закон о управним споровима" name="zakon" type="xs:string"/>
                    <xs:attribute default="Управни суд у Београду" name="sud" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="Ime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Prezime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="Razlog_zalbe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="непоступање"/>
            <xs:enumeration value="непоступање у целости"/>
            <xs:enumeration value="непоступање у законском року"/>
            <xs:enumeration value="одбијање/одбацивање"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Tip_odluke">
        <xs:restriction base="xs:string">
            <xs:enumeration value="основана"/>
            <xs:enumeration value="неоснована"/>
            <xs:enumeration value="поништена"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== fmilica/XML_i_web_servisi/servisi/organ-vlasti/backend/src/main/resources/data/schema/resenje/temp_resenje.xml
<res:Resenje xmlns="http://www.w3.org/ns/rdfa#" xmlns:res="http://resenje" xmlns:pred="http://www.xml.com/predicate/" xmlns:tipovi="http://tipovi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" about="http://resenje/b2fe25f8-abf3-4ea7-9727-1210afb795ba" broj_resenja="123" datum_resenja="2021-02-06" href="http://korisnik/igi.l.1999@gmail.com" id="http://resenje/b2fe25f8-abf3-4ea7-9727-1210afb795ba" rel="pred:vezanGradjanin" tip_odluke="основана" vocab="http://www.xml.com/predicate/" xsi:schemaLocation="http://resenje resenje.xsd">
   <res:Opis_zalbe razlog_zalbe="непоступање у законском року">Lorem Ipsum is simply <res:Ime_zalilac property="pred:zalilacIme">dummy text of the prin</res:Ime_zalilac>ting and typesetting<res:Prezime_zalilac property="pred:zalilacPrezime"> industry. Lorem Ip</res:Prezime_zalilac>sum has been the ind<res:Naziv_organa_vlasti property="pred:optuzeniNaziv">ustry's standard dumm</res:Naziv_organa_vlasti>y text ever sin<res:Mesto_organa_vlasti>ce the 1500s, when an un</res:Mesto_organa_vlasti>known printer too<res:Ulica_organa_vlasti>k a galley of type</res:Ulica_organa_vlasti>and scra<res:Ulicni_broj_organa_vlasti>mbled it to make a ty</res:Ulicni_broj_organa_vlasti>pe specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Opis_zalbe>
   <res:Odluka>
      <res:Nalog rok_izvrsenja="1">Lorem Ipsum is simply dummy text of the</res:Nalog>
      <res:Nalog rok_izvrsenja="1">printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Nalog>
   </res:Odluka>
   <res:Obrazlozenje>
      <res:Postupak_zalioca>
         <res:Podnosenje_zalbe about="http://resenje/b2fe25f8-abf3-4ea7-9727-1210afb795ba" datum_zalbe="2021-02-06" href="http://zalbacutanje/3bb777af-0ace-4ca9-a73f-9921c089a1e4" rel="pred:vezanaZalba" vocab="http://www.xml.com/predicate/">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Podnosenje_zalbe>
         <res:Podnosenje_zahteva about="http://resenje/b2fe25f8-abf3-4ea7-9727-1210afb795ba" datum_zahteva="2020-02-04" href="http://zahtev/063e9af2-d409-4d3d-9340-1fb18f0eb124" rel="pred:vezanZahtev" vocab="http://www.xml.com/predicate/">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Podnosenje_zahteva>
      </res:Postupak_zalioca>
      <res:Prosledjivanje_zalbe datum_prosledjivanja="2021-02-06">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Prosledjivanje_zalbe>
      <res:Izjasnjenje_o_zalbi datum_izjasnjenja="2021-02-06">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Izjasnjenje_o_zalbi>
      <res:Razlozi_odluke>
         <res:Detaljan_opis_podnetog_zahteva>Lorem Ipsum is simply dummy text of the </res:Detaljan_opis_podnetog_zahteva>printing and typesetting industry. Lorem Ipsum has been the <res:Detaljan_opis_odgovora_na_zahtev>industry's standard dummy tex</res:Detaljan_opis_odgovora_na_zahtev>t ever since the 1500s, when an unknown printer took a galley of <res:Detaljan_opis_odluke>type and scrambled it to m</res:Detaljan_opis_odluke>ake a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Razlozi_odluke>
      <res:Zalba_na_resenje rok_za_tuzbu="30" sud="Управни суд у Београду" taksa_tuzbe="390.0" zakon="Закон о управним споровима">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</res:Zalba_na_resenje>
   </res:Obrazlozenje>
   <res:Poverenik>
      <res:Ime property="pred:izdavacIme">Мика</res:Ime>
      <res:Prezime property="pred:izdavacPrezime">Микић</res:Prezime>
   </res:Poverenik>
</res:Resenje>

=== fmilica/XML_i_web_servisi/servisi/poverenik/backend/src/main/resources/data/schema/resenje/temp_resenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<res:Resenje xmlns:res="http://resenje" xmlns="http://www.w3.org/ns/rdfa#" xmlns:pred="http://www.xml.com/predicate/" xmlns:tipovi="http://tipovi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" about="http://resenje/c4161830-f4e9-42fc-a881-62830fc3bb87" broj_resenja="11" datum_resenja="2021-02-06" href="http://korisnik/pera@pera.com" id="http://resenje/c4161830-f4e9-42fc-a881-62830fc3bb87" rel="pred:vezanGradjanin" tip_odluke="основана" vocab="http://www.xml.com/predicate/" xsi:schemaLocation="http://resenje resenje.xsd">
  <res:Opis_zalbe razlog_zalbe="непоступање">
    <res:Ime_zalilac property="pred:zalilacIme">Lorem Ipsum is simpl</res:Ime_zalilac>y dummy text<res:Prezime_zalilac property="pred:zalilacPrezime"> of the printin</res:Prezime_zalilac>g and typesetting industry.<res:Naziv_organa_vlasti property="pred:optuzeniNaziv"> Lorem Ipsum</res:Naziv_organa_vlasti> has been the industry's standard dummy text ever si<res:Mesto_organa_vlasti>nce the 1500</res:Mesto_organa_vlasti>s, when an unk<res:Ulica_organa_vlasti>nown printer took a galley of</res:Ulica_organa_vlasti>type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into <res:Ulicni_broj_organa_vlasti>electroni</res:Ulicni_broj_organa_vlasti>c typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Opis_zalbe>
  <res:Odluka>Lorem Ipsum is simply dummy text of t<res:Nalog rok_izvrsenja="2">he printing and typese</res:Nalog>tting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining esse<res:Nalog rok_izvrsenja="2">ntially</res:Nalog>unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Odluka>
  <res:Obrazlozenje>
    <res:Postupak_zalioca>
      <res:Podnosenje_zalbe about="http://resenje/c4161830-f4e9-42fc-a881-62830fc3bb87" datum_zalbe="2020-01-01" href="http://zalbaodbijanje/38111d5e-29fe-4d7a-b529-72dfceb567d5" rel="pred:vezanaZalba" vocab="http://www.xml.com/predicate/">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Podnosenje_zalbe>
      <res:Podnosenje_zahteva about="http://resenje/c4161830-f4e9-42fc-a881-62830fc3bb87" datum_zahteva="2020-01-01" href="http://zahtev/5f408717-0126-43c4-a232-d0bd6efc4d2b" rel="pred:vezanZahtev" vocab="http://www.xml.com/predicate/">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Podnosenje_zahteva>
    </res:Postupak_zalioca>
    <res:Prosledjivanje_zalbe datum_prosledjivanja="2021-02-04">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Prosledjivanje_zalbe>
    <res:Izjasnjenje_o_zalbi datum_izjasnjenja="2021-02-04">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Izjasnjenje_o_zalbi>
    <res:Razlozi_odluke>Lorem Ipsum is simply dummy <res:Detaljan_opis_podnetog_zahteva>text of the printing and ty</res:Detaljan_opis_podnetog_zahteva>pesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scramble<res:Detaljan_opis_odgovora_na_zahtev>d it to make a t</res:Detaljan_opis_odgovora_na_zahtev>ype specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the r<res:Detaljan_opis_odluke>elease of Le</res:Detaljan_opis_odluke>traset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Razlozi_odluke>
    <res:Zalba_na_resenje rok_za_tuzbu="30" sud="Управни суд у Београду" taksa_tuzbe="390" zakon="Закон о управним споровима">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Zalba_na_resenje>
  </res:Obrazlozenje>
  <res:Poverenik>
    <res:Ime property="pred:izdavacIme">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Ime>
    <res:Prezime property="pred:izdavacPrezime">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</res:Prezime>
  </res:Poverenik>
</res:Resenje>
