=== fmilica/XML_i_web_servisi/backend/poverenik/src/main/resources/data/schema/zahtev/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://zahtev" xmlns:zahtev="http://zahtev">

    <xs:element name="Zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Organ_vlasti" type="zahtev:TOrgan_vlasti"/>
                <xs:element ref="zahtev:Telo_zahteva"> </xs:element>
                <xs:element name="Trazilac" type="zahtev:TTrazilac"> </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
            <xs:attribute name="mesto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([A-Z][a-z]+)(\s[A-Z][a-z]+)*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="datum" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Telo_zahteva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Zakonska_osnova" type="zahtev:TZakonska_osnova"> </xs:element>
                <xs:element ref="zahtev:Zahtevi"> </xs:element>
                <xs:element name="Zahtevane_informacije" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zahtevi">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Obavestenje"/>
                <xs:element minOccurs="0" name="Uvid"/>
                <xs:element minOccurs="0" name="Kopija"/>
                <xs:element minOccurs="0" name="Dostavljanje_kopije">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="zahtev:Nacin_dostave"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Nacin_dostave">
        <xs:complexType>
            <xs:choice>
                <xs:element name="Dostava_postom"/>
                <xs:element name="Dostava_elektronskom_postom"/>
                <xs:element name="Dostava_faksom"/>
                <xs:element name="Posebna_dostava">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nacin_posebne_dostave">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TOrgan_vlasti">
        <xs:sequence>
            <xs:element name="Naziv_organa" type="xs:string"/>
            <xs:element name="Sediste_organa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([A-Z][a-z]+)(\s[A-Z][a-z]+)*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TTrazilac">
        <xs:sequence>
            <xs:element name="Ime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Prezime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Adresa" type="xs:string"/>
            <xs:element name="Kontakt_podaci" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TZakonska_osnova">
        <xs:sequence>
            <xs:element name="Clan" fixed="15" type="xs:positiveInteger"/>
            <xs:element name="Stav" fixed="1" type="xs:positiveInteger"/>
            <xs:element name="Zakon"
                fixed="Zakon o slobodnom pristupu informacijama od javnog značaja" type="xs:string"/>
            <xs:element name="Sluzbeni_glasnik">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Naziv" fixed="Službeni glasnik RS" type="xs:string"/>
                        <xs:element name="Brojevi">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element maxOccurs="unbounded" name="Broj">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[1-9][0-9]*\/([0-9]){2}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== fmilica/XML_i_web_servisi/servisi/poverenik/backend/src/main/resources/data/zahtev_gen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev:Zahtev xmlns="http://www.w3.org/ns/rdfa#"
    xmlns:zahtev="http://zahtev"
    xmlns:tipovi="http://tipovi"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.xml.com/predicate/"
    xsi:schemaLocation="http://zahtev schema/zahtev/zahtev.xsd" 
    mesto="Sremska Mitrovica" 
    datum="2022-04-06"
    razresen="false"
    id="ID1"
    vocab="http://www.xml.com/predicate/"
    about="http://zahtev/ID1"
    rel="pred:vezanGradjanin"
    href="http://korisnik/pera@pera.com">
    <zahtev:Organ_vlasti>
        <tipovi:Naziv property="pred:primalacNaziv">Fakultet tehnickih nauka</tipovi:Naziv>
        <tipovi:Sediste>Novi Sad</tipovi:Sediste>
    </zahtev:Organ_vlasti>
    <zahtev:Telo_zahteva>
        <zahtev:Zakonska_osnova>
            <zahtev:Clan>15</zahtev:Clan>
            <zahtev:Stav>1</zahtev:Stav>
            <zahtev:Zakon>Zakon o slobodnom pristupu informacijama od javnog značaja</zahtev:Zakon>
            <zahtev:Sluzbeni_glasnik>
                <tipovi:Naziv>Službeni glasnik RS</tipovi:Naziv>
                <tipovi:Brojevi>
                    <tipovi:Broj>120/04</tipovi:Broj>
                    <tipovi:Broj>54/07</tipovi:Broj>
                    <tipovi:Broj>104/09</tipovi:Broj>
                    <tipovi:Broj>36/10</tipovi:Broj>
                </tipovi:Brojevi>
            </zahtev:Sluzbeni_glasnik>
        </zahtev:Zakonska_osnova>
        <zahtev:Zahtevi>
            <zahtev:Obavestenje>
            </zahtev:Obavestenje>
            <zahtev:Kopija>
            </zahtev:Kopija>
            <zahtev:Dostavljanje_kopije>
                <zahtev:Nacin_dostave>
                    <zahtev:Posebna_dostava>
                        <zahtev:Nacin_posebne_dostave>Golubom pismonosom</zahtev:Nacin_posebne_dostave>
                    </zahtev:Posebna_dostava>
                </zahtev:Nacin_dostave>
            </zahtev:Dostavljanje_kopije>
        </zahtev:Zahtevi>
        <zahtev:Zahtevane_informacije>Informacije o polozenim predmetima</zahtev:Zahtevane_informacije>
    </zahtev:Telo_zahteva>
    <zahtev:Trazilac>
        <tipovi:Ime property="pred:podnosilacIme">Vlastislav</tipovi:Ime>
        <tipovi:Prezime property="pred:podnosilacPrezime">Jakovljevic</tipovi:Prezime>
        <tipovi:Adresa>
            <tipovi:Mesto>Novi Sad</tipovi:Mesto>
            <tipovi:Ulica>Zeleznicka</tipovi:Ulica>
            <tipovi:Ulicni_broj>23</tipovi:Ulicni_broj>
        </tipovi:Adresa>
        <tipovi:Kontakt_podaci>063/452498506</tipovi:Kontakt_podaci>
    </zahtev:Trazilac>
</zahtev:Zahtev>
