=== fmilica/XML_i_web_servisi/servisi/poverenik/backend/src/main/resources/data/schema/resenje/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://resenje" xmlns:res="http://resenje" xmlns:tipovi="http://tipovi"
    xmlns:rdfa="http://www.w3.org/ns/rdfa#"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
    <xs:import namespace="http://tipovi" schemaLocation="../tipovi.xsd"/>
    <xs:element name="Resenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="res:Opis_zalbe"/>
                <xs:element ref="res:Odluka"/>
                <xs:element ref="res:Obrazlozenje"/>
                <xs:element name="Poverenik" type="res:TOsoba"/>
            </xs:sequence>
            <xs:attribute name="broj_resenja" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{2}-\d{4}\/\d{4}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="datum_resenja" type="xs:date" use="required"/>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="vocab" type="xs:string"/>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Opis_zalbe">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="Podnosilac_zalbe" type="res:TOsoba"/>
                <xs:element name="Organ_vlasti" type="tipovi:TOrgan_vlasti_adresa"/>
                <xs:element name="Zakonska_osnova_resenja" type="res:TZakonske_osnove"/>
            </xs:sequence>
            <xs:attribute name="razlog_zalbe" type="res:Razlog_zalbe" use="required"/>
            <xs:attribute name="datum_zahteva" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odluka">
        <xs:complexType>
            <xs:choice>
                <xs:element name="Nalozi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="res:Nalog"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Odbijanje">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="razlog_odbijanja" type="res:Tip_resenja"
                                    use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Nalog">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="rok_izvrsenja" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Obrazlozenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="res:Postupak_zalioca"/>
                <xs:element ref="res:Prosledjivanje_zalbe"/>
                <xs:element ref="res:Odgovor_na_zalbu"/>
                <xs:element ref="res:Razlozi_odluke"/>
                <xs:element ref="res:Zalba_na_resenje"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Postupak_zalioca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podnosenje_zalbe">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="datum_zalbe" type="xs:date" use="required"/>
                                <xs:attribute name="vocab" type="xs:string"/>
                                <xs:attribute name="about" type="xs:string"/>
                                <xs:attribute name="rel" type="xs:string"/>
                                <xs:attribute name="href" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podnosenje_zahteva">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="datum_zahteva" type="xs:date" use="required"/>
                                <xs:attribute name="vocab" type="xs:string"/>
                                <xs:attribute name="about" type="xs:string"/>
                                <xs:attribute name="rel" type="xs:string"/>
                                <xs:attribute name="href" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="prilozene_kopije" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Prosledjivanje_zalbe">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="Zakonska_osnova_prosledjivanja" type="res:TZakonske_osnove"/>
            </xs:sequence>
            <xs:attribute name="datum_prosledjivanja" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odgovor_na_zalbu">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="datum_odgovora" type="xs:date"/>
                    <xs:attribute name="rok_za_odgovor" type="xs:positiveInteger"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Razlozi_odluke">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="Detaljan_opis_podnetog_zahteva" type="xs:string"/>
                <xs:element name="Detaljan_opis_odgovora_na_zahtev">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="Zakonska_osnova_odgovora" type="res:TZakonske_osnove"
                            />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Obrazlozenje_odluke">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Detaljan_opis_odluke" type="xs:string"/>
                            <xs:element name="Zakonske_osnove_odluke" type="res:TZakonske_osnove"/>
                        </xs:sequence>
                        <xs:attribute name="tip_odluke" type="res:Tip_resenja" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element
        default="Против овог решења није допуштена жалба већ се, у складу са Законом о управним споровима, може покренути управни спор тужбом Управном суду у Београду, у року од 30 дана од дана пријема решења. Такса на тужбу износи 390,00 динара."
        name="Zalba_na_resenje">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute default="30" name="rok_za_tuzbu" type="xs:positiveInteger"/>
                    <xs:attribute default="390.00" name="taksa_tuzbe" type="xs:double"/>
                    <xs:attribute default="Закон о управним споровима" name="zakon" type="xs:string"/>
                    <xs:attribute default="Управни суд у Београду" name="sud" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TZakonska_osnova">
        <xs:sequence>
            <xs:element name="Clan" type="xs:positiveInteger"/>
            <xs:element minOccurs="0" name="Stav" type="xs:positiveInteger"/>
            <xs:element minOccurs="0" name="Tacka" type="xs:positiveInteger"/>
            <xs:element name="Zakon" type="xs:string"/>
            <xs:element minOccurs="0" name="Sluzbeni_glasnik" type="tipovi:TSluzbeni_glasnik">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="rok" type="xs:positiveInteger"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TZakonske_osnove">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="Zakonska_osnova" type="res:TZakonska_osnova"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="Ime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Prezime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="Razlog_zalbe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nepostupanje"/>
            <xs:enumeration value="nepostupanje u celosti"/>
            <xs:enumeration value="nepostupanje u zakonskom roku"/>
            <xs:enumeration value="odbijanje/odbacivanje"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Tip_resenja">
        <xs:restriction base="xs:string">
            <xs:enumeration value="osnovana"/>
            <xs:enumeration value="neosnovana"/>
            <xs:enumeration value="ponistena"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== fmilica/XML_i_web_servisi/XML_POC/data/marshalled/resenje_marsh.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Resenje xmlns="http://resenje" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" broj_resenja="000-00-0000/0000-00" datum_resenja="2006-05-04" id="ID001" xsi:schemaLocation="http://resenje resenje.xsd">
      
  <Opis_zalbe datum_zahteva="2006-05-04" razlog_zalbe="nepostupanje">
            Повереник за информације од јавног значаја и заштиту података о личности, 
        у поступку по алби коју је изјавио AA, због непоступања Учитељског факултета 
        у Призрену са привременим седиштем у Лепосавићу, ул. Немањина бб, 
        по његовом захтеву од 16.04.2020. године за приступ информацијама од 
        јавног значаја, на основу члана 35. став 1. тачка 5. Закона о слободном приступу
        информацијама од јавног значаја („Сл. гласник РС“, бр. 120/04, 54/07, 104/09 и 36/10),
        а у вези са чланом 4. тачка 22. Закона о заштити података о личности 
        („Сл. гласник РС“, број 87/18), као и члана 23. и члана 24. став 4. 
        Закона о слободном приступу информацијама од јавног значаја и члана 173. став 2. 
        Закона о општем управном поступку („Сл. гласник РС“, бр. 18/2016 и 95/2018-аутентично тумачење), 
        доноси
        
    <Podnosilac_zalbe>
                  
      <Ime>Mihailo</Ime>
                  
      <Prezime>Grujic</Prezime>
              
    </Podnosilac_zalbe>
            
    <Organ_vlasti>
                  
      <Naziv_organa>Uciteljski fakultet u Prizrenu</Naziv_organa>
                  
      <Sediste_organa>
                        
        <Mesto>Leposavic</Mesto>
                        
        <Ulica>Nemanjina</Ulica>
                        
        <Ulicni_broj>bb</Ulicni_broj>
                    
      </Sediste_organa>
              
    </Organ_vlasti>
            
    <Zakonska_osnova_resenja>
                  
      <Zakonska_osnova>
                        
        <Clan>35</Clan>
                        
        <Stav>1</Stav>
                        
        <Tacka>5</Tacka>
                        
        <Zakon>Закона о слободном приступу информацијама од јавног значаја</Zakon>
                        
        <Sluzbeni_glasnik>
                              
          <Naziv>Službeni glasnik RS</Naziv>
                              
          <Brojevi>
                                    
            <Broj>120/04</Broj>
                                    
            <Broj>54/07</Broj>
                                    
            <Broj>104/09</Broj>
                                    
            <Broj>36/10</Broj>
                                
          </Brojevi>
                          
        </Sluzbeni_glasnik>
                    
      </Zakonska_osnova>
                  
      <Zakonska_osnova>
                        
        <Clan>4</Clan>
                        
        <Tacka>22</Tacka>
                        
        <Zakon>Закона о заштити података о личности</Zakon>
                        
        <Sluzbeni_glasnik>
                              
          <Naziv>Službeni glasnik RS</Naziv>
                              
          <Brojevi>
                                    
            <Broj>87/18</Broj>
                                
          </Brojevi>
                          
        </Sluzbeni_glasnik>
                    
      </Zakonska_osnova>
                  
      <Zakonska_osnova>
                        
        <Clan>23</Clan>
                        
        <Zakon>Закона о слободном приступу информацијама од јавног значаја</Zakon>
                    
      </Zakonska_osnova>
                  
      <Zakonska_osnova>
                        
        <Clan>24</Clan>
                        
        <Stav>4</Stav>
                        
        <Zakon>Закона о слободном приступу информацијама од јавног значаја</Zakon>
                    
      </Zakonska_osnova>
                  
      <Zakonska_osnova>
                        
        <Clan>173</Clan>
                        
        <Stav>2</Stav>
                        
        <Zakon>Закона о општем управном поступку</Zakon>
                        
        <Sluzbeni_glasnik>
                              
          <Naziv>Službeni glasnik RS</Naziv>
                              
          <Brojevi>
                                    
            <Broj>18/16</Broj>
                                    
            <Broj>95/18</Broj>
                                
          </Brojevi>
                          
        </Sluzbeni_glasnik>
                    
      </Zakonska_osnova>
              
    </Zakonska_osnova_resenja>
        
  </Opis_zalbe>
      
  <Odluka>
            
    <Nalozi>
                  
      <Nalog rok_izvrsenja="5">
                I Налаже се Учитељском факултету у Призрену са привременим 
                седиштем у Лепосавићу, да без одлагања, а најкасније у року 
                од пет дана од дана пријема овог решења, обавести АА, 
                да ли поседује тражене информације односно документ у 
                коме су исте садржане, и то: Уговор о раду који је као последњи
                потписан између тог Факултета и ББ, те да му, уколико такав 
                документ поседује достави копију истог електронском поштом на
                адресу … или поштом, с тим што ће пре достављања заштитити и 
                учинити недоступним податке о личности којима би се повредило 
                право на приватност лица на које се информације односе, 
                као што су: адреса становања, лични матични број грађана, име 
                оца, радни стаж, просечна оцена студирања и сл. уколико су 
                такви подаци садржани у траженом документу.
            </Nalog>
                  
      <Nalog rok_izvrsenja="7">
                II О извршењу решења Учитељски факултет у Призрену са привременим
                седиштем у Лепосавићу, ће обавестити Повереника у року од седам 
                дана од пријема овог решења.
            </Nalog>
              
    </Nalozi>
        
  </Odluka>
      
  <Obrazlozenje>
            
    <Postupak_zalioca prilozene_kopije="true">
                  
      <Podnosenje_zalbe datum_zalbe="2020-05-07">
                АА, као тражилац информација, изјавио је дана 07.05.2020. 
                године жалбу Поверенику, због непоступања Учитељског факултета 
                у Призрену са привременим седиштем у Лепосавићу
            </Podnosenje_zalbe>
                  
      <Podnosenje_zahteva datum_zahteva="2020-04-16">
                по његовом захтеву од 16.04.2020. године за приступ информацијама
                од јавног значаја и у прилогу доставио копију истог.
            </Podnosenje_zahteva>
              
    </Postupak_zalioca>
            
    <Prosledjivanje_zalbe datum_prosledjivanja="2020-05-11">
                  Поступајући по жалби, Повереник је дана 11.05.2020. године упутио 
            исту на изјашњење Учитељском факултету у Призрену са привременим 
            седиштем у Лепосавићу, као органу власти у смислу члана 3. 
            Закона о слободном приступу информацијама од јавног значаја и
            затражио да се изјасни о наводима жалбе, посебно о разлозима 
            непоступања у законском року по поднетом захтеву у складу са 
            одредбама члана 16. ст.1-9. или ст. 10. Закона,
            
      <Zakonska_osnova_prosledjivanja>
                        
        <Zakonska_osnova>
                              
          <Clan>3</Clan>
                              
          <Zakon>Закон о слободном приступу информацијама од јавног значаја</Zakon>
                          
        </Zakonska_osnova>
                        
        <Zakonska_osnova>
                              
          <Clan>16</Clan>
                              
          <Stav>10</Stav>
                              
          <Zakon>Закон о слободном приступу информацијама од јавног значаја</Zakon>
                          
        </Zakonska_osnova>
                    
      </Zakonska_osnova_prosledjivanja>
              
    </Prosledjivanje_zalbe>
            
    <Odgovor_na_zalbu rok_za_odgovor="8">
            поводом чега није добио одговор.
        </Odgovor_na_zalbu>
            
    <Razlozi_odluke>
                  По разматрању жалбе и осталих списа овог предмета, 
            донета је одлука као у диспозитиву решења из следећих разлога:
            
      <Detaljan_opis_podnetog_zahteva>
                Увидом у списе предмета утврђено је да је АА, дана 16.04.2020. године, 
                поднео Учитељском факултету у Призрену са привременим седиштем у Лепосавићу, 
                захтев за приступ информацијама од јавног значаја, електронском поштом, 
                којим је тражио информације од јавног значаја, ближе наведенe у ставу 
                I диспозитива овог решења.
            </Detaljan_opis_podnetog_zahteva>
                  
      <Detaljan_opis_odgovora_na_zahtev>
                        Такође је увидом у списе предмета утврђено да по захтеву жалиоца 
                од 16.04.2020. године, орган власти није поступио, што је био дужан да 
                учини без одлагања, а најкасније у року од 15 дана од пријема захтева 
                те да жалиоца, у смислу члана 16. став 1. Закона о слободном приступу 
                информацијама од јавног значаја, обавести да ли поседује тражене 
                информације и да му, уколико исте поседује, стави на увид документ 
                који исте садржи односно изда му или достави копију документа у коме 
                су тражене информације садржане, или да у супротном донесе решење о 
                одбијању захтева, у смислу става 10. истог члана.
                
        <Zakonska_osnova_odgovora>
                              
          <Zakonska_osnova>
                                    
            <Clan>16</Clan>
