=== fmilica/XML_i_web_servisi/XML_POC/data/zalba_cutanje/zalbacutanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://zalbacutanje" xmlns:obavestenje="http://obavestenje"
    xmlns:zalbacutanje="http://zalbacutanje" xmlns:zhtv="http://zahtev">
    <xs:element name="Zalba_cutanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="zalbacutanje:Primalac_zalbe"/>
                <xs:element ref="zalbacutanje:Zalba"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
            <xs:attribute name="datum" type="xs:date"/>
            <xs:attribute name="mesto" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Primalac_zalbe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naziv_primaoca"
                    fixed="Povereniku za informacije od javnog znacaja i zastitu podataka o licnosti"
                    type="xs:string"/>
                <xs:element ref="zalbacutanje:Adresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="39000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zalba">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Clan">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Zakon" type="xs:string"/>
                <xs:element name="Naziv_organa" type="xs:string"/>
                <xs:element name="Razlog_zalbe">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Nije postupio"/>
                            <xs:enumeration value="Nije postupio u celosti"/>
                            <xs:enumeration value="U zakonskom roku"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum" type="xs:date"/>
                <xs:element name="Podaci_o_zahtevu" type="xs:string"/>
                <xs:element ref="zalbacutanje:Podnosilac_zalbe"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podnosilac_zalbe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime" type="xs:string"/>
                <xs:element name="Prezime" type="xs:string"/>
                <xs:element ref="zalbacutanje:Adresa"/>
                <xs:element name="Drugi_podaci" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fmilica/XML_i_web_servisi/modelovani_dokumenti/zalba_cutanje/zalbacutanje_gen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zalba_cutanje xmlns="http://zalbacutanje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://zalbacutanje file:/C:/Users/admin/Desktop/xmlproj/XML_i_web_servisi/modelovani_dokumenti/zalba_cutanje/zalbacutanje.xsd"
    mesto="Novi Sad" datum="2020-12-07">
    <Primalac_zalbe>
        <Naziv_primaoca>Povereniku za informacije od javnog znacaja i zastitu podataka o licnosti</Naziv_primaoca>
        <Adresa>
            <Mesto>Beograd</Mesto>
            <Postanski_broj>11000</Postanski_broj>
            <Ulica>Bulevar kralja Aleksandra</Ulica>
            <Broj>15</Broj>
        </Adresa>
    </Primalac_zalbe>
    <Zalba>
        <Clan>22</Clan>
        <Zakon>Zakona o slobodnom pristupu informacijama od javnog znacaja</Zakon>
        <Naziv_organa>Fakultet tehnickih nauka</Naziv_organa>
        <Razlog_zalbe>Nije postupio</Razlog_zalbe>
        <Datum>2020-11-13</Datum>
        <Podaci_o_zahtevu>Zahtevane informacije o polozenim predmetima Vlastislava Jakovljevica</Podaci_o_zahtevu>
        <Podnosilac_zalbe>
            <Ime>Vlastislav</Ime>
            <Prezime>Jakovljevic</Prezime>
            <Adresa>
                <Mesto>Novi Sad</Mesto>
                <Postanski_broj>21000</Postanski_broj>
                <Ulica>Zeleznicka</Ulica>
                <Broj>23</Broj>
            </Adresa>
            <Drugi_podaci>Kontakt telefon: 063/452498506</Drugi_podaci>
        </Podnosilac_zalbe>
    </Zalba>
</Zalba_cutanje>
